#!/usr/bin/env bash
#
# setup.sh — single-command install for calendar-plan-skill (Claude + Codex).
#
# Run after cloning:
#   bash setup.sh
#
# Reads local.env (creates from template on first run), then:
#   1. Symlinks ~/.claude/skills/calendar-plan -> this repo
#   2. Generates skills/calendar-plan/config/{settings.conf, mcp-config.json}
#   3. Seeds planning-preferences.md if missing
#   4. Seeds prompts/cron-prompt.md if missing
#   5. Bootstraps Codex install (skill files + automation.toml)
#   6. Symlinks memory.md so both runtimes share one log
#   7. Runs doctor.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$REPO_DIR/local.env"
ENV_EXAMPLE="$REPO_DIR/local.env.example"
SKILL_DIR="$REPO_DIR/skills/calendar-plan"
CLAUDE_INSTALL="$HOME/.claude/skills/calendar-plan"
CODEX_INSTALL="$HOME/.codex/skills/calendar-plan"
CODEX_AUTO="$HOME/.codex/automations/calendar-plan"

if [[ -t 1 ]]; then
  B=$'\e[1m'; D=$'\e[2m'; R=$'\e[31m'; G=$'\e[32m'; Y=$'\e[33m'; BL=$'\e[34m'; X=$'\e[0m'
else
  B=; D=; R=; G=; Y=; BL=; X=
fi
heading() { echo; echo "${B}${BL}== $1 ==${X}"; }
ok()      { echo "  ${G}OK${X}  $*"; }
warn()    { echo "  ${Y}WARN${X}  $*"; }
fail()    { echo "  ${R}FAIL${X}  $*"; }
skip()    { echo "  ${D}skip${X}  $*"; }

# ============================================================
# 0. local.env bootstrap
# ============================================================
heading "0. local.env"
if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$ENV_EXAMPLE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    fail "$ENV_FILE didn't exist — created from template."
    echo
    echo "  Now edit it with your real values:"
    echo "    \$EDITOR $ENV_FILE"
    echo
    echo "  Then re-run:"
    echo "    bash $0"
    exit 1
  else
    fail "neither $ENV_FILE nor $ENV_EXAMPLE found. Re-clone the repo."
    exit 1
  fi
fi

# Validate the file isn't still the template
if grep -q '<you>\|<paste-your-integration-token-here>' "$ENV_FILE"; then
  fail "$ENV_FILE still contains <placeholder> values."
  echo "  Fill in real values, then re-run."
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a
ok "loaded $ENV_FILE"

# Defaults for optional vars
: "${MODEL:=claude-sonnet-4-6}"
: "${TIMEZONE:=America/New_York}"
: "${CRON_HOUR:=22}"
: "${DEFAULT_MODE:=auto}"
: "${EXTRA_ADD_DIRS:=}"
: "${CODEX_MODEL:=gpt-5.5}"
: "${CODEX_REASONING:=xhigh}"
: "${CODEX_CWD:=$OBSIDIAN_VAULT_ROOT}"

# ============================================================
# 1. Prereqs
# ============================================================
heading "1. Prereqs"
for cmd in claude npx python3; do
  if command -v "$cmd" >/dev/null 2>&1; then ok "$cmd: $("$cmd" --version 2>&1 | head -1)"
  else fail "$cmd not on PATH"; exit 1; fi
done

# ============================================================
# 2. Symlink Claude skill
# ============================================================
heading "2. Claude install"
if [[ -L "$CLAUDE_INSTALL" ]]; then
  ok "already symlinked: $CLAUDE_INSTALL -> $(readlink "$CLAUDE_INSTALL")"
elif [[ -d "$CLAUDE_INSTALL" ]]; then
  warn "$CLAUDE_INSTALL exists and is not a symlink. Leaving it alone."
else
  mkdir -p "$(dirname "$CLAUDE_INSTALL")"
  ln -s "$SKILL_DIR" "$CLAUDE_INSTALL"
  ok "symlinked $CLAUDE_INSTALL -> $SKILL_DIR"
fi

# ============================================================
# 3. settings.conf (derived)
# ============================================================
heading "3. settings.conf (derived from local.env)"
mkdir -p "$SKILL_DIR/config"
cat > "$SKILL_DIR/config/settings.conf" <<EOF
# Auto-generated by setup.sh from local.env. Do not edit by hand — edit local.env instead.
MODEL="$MODEL"
TIMEZONE="$TIMEZONE"
CRON_HOUR="$CRON_HOUR"
CALENDAR_CONTEXT="$CALENDAR_CONTEXT_PATH"
TASK_SOURCE_NAME="$NOTION_PAGE_TITLE"
DEFAULT_MODE="$DEFAULT_MODE"
EXTRA_ADD_DIRS="$EXTRA_ADD_DIRS"
EOF
chmod 600 "$SKILL_DIR/config/settings.conf"
ok "wrote $SKILL_DIR/config/settings.conf (chmod 600)"

# ============================================================
# 4. mcp-config.json (derived)
# ============================================================
heading "4. mcp-config.json (derived from local.env)"
cat > "$SKILL_DIR/config/mcp-config.json" <<EOF
{
  "_generated": "by setup.sh from local.env on $(date -u '+%Y-%m-%dT%H:%M:%SZ'). Do not edit by hand — edit local.env instead.",
  "mcpServers": {
    "notion": {
      "command": "npx",
      "args": ["-y", "@notionhq/notion-mcp-server"],
      "env": {
        "OPENAPI_MCP_HEADERS": "{\"Authorization\":\"Bearer $NOTION_TOKEN\",\"Notion-Version\":\"2022-06-28\"}"
      }
    },
    "google-calendar": {
      "command": "npx",
      "args": ["-y", "@cocal/google-calendar-mcp"],
      "env": { "GOOGLE_OAUTH_CREDENTIALS": "$GCAL_CREDENTIALS_PATH" }
    },
    "gmail": {
      "command": "npx",
      "args": ["-y", "@gongrzhe/server-gmail-autoauth-mcp"],
      "env": {
        "GMAIL_OAUTH_PATH": "$GMAIL_CREDENTIALS_PATH",
        "GMAIL_CREDENTIALS_PATH": "$GMAIL_TOKEN_PATH"
      }
    },
    "filesystem-vault": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "$OBSIDIAN_VAULT_ROOT"]
    }
  }
}
EOF
chmod 600 "$SKILL_DIR/config/mcp-config.json"
python3 -c "import json; json.load(open('$SKILL_DIR/config/mcp-config.json'))" \
  && ok "wrote $SKILL_DIR/config/mcp-config.json (chmod 600, valid JSON)" \
  || { fail "generated mcp-config.json is invalid JSON"; exit 1; }

# ============================================================
# 5. planning-preferences.md seed (canonical = Codex side)
# ============================================================
heading "5. planning-preferences.md"
PREFS_REAL="$CODEX_INSTALL/planning-preferences.md"
PREFS_LINK="$SKILL_DIR/config/planning-preferences.md"
mkdir -p "$CODEX_INSTALL"
if [[ ! -f "$PREFS_REAL" ]]; then
  cp "$REPO_DIR/examples/planning-preferences.example.md" "$PREFS_REAL"
  chmod 600 "$PREFS_REAL"
  warn "seeded $PREFS_REAL from example — EDIT IT with your real calendar IDs"
  echo "       \$EDITOR $PREFS_REAL"
else
  ok "$PREFS_REAL already exists, keeping"
fi
if [[ -L "$PREFS_LINK" || -f "$PREFS_LINK" ]]; then
  rm "$PREFS_LINK" 2>/dev/null || true
fi
ln -s "$PREFS_REAL" "$PREFS_LINK"
ok "linked $PREFS_LINK -> $PREFS_REAL"

# ============================================================
# 6. cron-prompt.md seed (from .example)
# ============================================================
heading "6. cron-prompt.md"
PROMPT_REAL="$REPO_DIR/prompts/cron-prompt.md"
PROMPT_EX="$REPO_DIR/prompts/cron-prompt.example.md"
if [[ ! -f "$PROMPT_REAL" ]]; then
  cp "$PROMPT_EX" "$PROMPT_REAL"
  ok "seeded $PROMPT_REAL from .example"
else
  ok "$PROMPT_REAL already exists, keeping"
fi

# ============================================================
# 7. Codex install
# ============================================================
heading "7. Codex install"
mkdir -p "$CODEX_INSTALL/agents" "$CODEX_AUTO"

cp "$REPO_DIR/codex/SKILL.md"                  "$CODEX_INSTALL/SKILL.md"
cp "$REPO_DIR/codex/agents/openai.example.yaml" "$CODEX_INSTALL/agents/openai.yaml"
ok "copied $CODEX_INSTALL/SKILL.md and agents/openai.yaml"

# Render automation.toml from cron-prompt.md + local.env values
python3 - <<PYEOF
import pathlib, re
prompt_md = pathlib.Path("$PROMPT_REAL").read_text(encoding="utf-8")
body = prompt_md.split("\n---\n", 1)[1].lstrip() if "\n---\n" in prompt_md else prompt_md
body = (body
    .replace("{{SKILL_DIR}}",        "$CODEX_INSTALL")
    .replace("{{PLANNING_PREFS}}",   "$PREFS_REAL")
    .replace("{{MEMORY_FILE}}",      "$CODEX_AUTO/memory.md")
    .replace("{{CALENDAR_CONTEXT}}", "$CALENDAR_CONTEXT_PATH")
    .replace("{{TASK_SOURCE_NAME}}", "$NOTION_PAGE_TITLE")
    .replace("{{TIMEZONE}}",         "$TIMEZONE")
    .replace("{{CRON_HOUR}}",        "$CRON_HOUR")
    .replace("{{TARGET_DATE}}", "").replace("{{MODE}}", "auto")
    .rstrip())
body_safe = body.replace('"""', '\\"\\"\\"')

toml = pathlib.Path("$REPO_DIR/codex/automation.example.toml").read_text(encoding="utf-8")
toml = (toml
    .replace("{{PROMPT_BODY}}",      body_safe)
    .replace("{{CODEX_SKILL_DIR}}",  "$CODEX_INSTALL")
    .replace("{{CODEX_AUTO_DIR}}",   "$CODEX_AUTO")
    .replace("{{CALENDAR_CONTEXT}}", "$CALENDAR_CONTEXT_PATH")
    .replace("{{TASK_SOURCE_NAME}}", "$NOTION_PAGE_TITLE")
    .replace("{{TIMEZONE}}",         "$TIMEZONE")
    .replace("{{CRON_HOUR}}",        "$CRON_HOUR")
    .replace("{{CODEX_CWD}}",        "$CODEX_CWD")
    .replace("{{CODEX_MODEL}}",      "$CODEX_MODEL")
    .replace("{{CODEX_REASONING}}",  "$CODEX_REASONING"))

# Default to INACTIVE — user opts in to the cron explicitly.
toml = re.sub(r'^status\s*=\s*".*"', 'status = "INACTIVE"', toml, count=1, flags=re.MULTILINE)

out = pathlib.Path("$CODEX_AUTO/automation.toml")
out.write_text(toml, encoding="utf-8")
print(f"  wrote $CODEX_AUTO/automation.toml (status=INACTIVE — set ACTIVE later to enable cron)")
PYEOF
ok "rendered automation.toml (cron INACTIVE — opt in by editing status)"

# ============================================================
# 8. Memory: shared between runtimes
# ============================================================
heading "8. memory.md (shared between runtimes)"
CLAUDE_MEM="$SKILL_DIR/memory/memory.md"
CODEX_MEM="$CODEX_AUTO/memory.md"
mkdir -p "$SKILL_DIR/memory"
if [[ ! -f "$CODEX_MEM" ]]; then
  cp "$REPO_DIR/examples/memory.example.md" "$CODEX_MEM"
  chmod 600 "$CODEX_MEM"
  ok "seeded $CODEX_MEM from example"
fi
if [[ -L "$CLAUDE_MEM" ]]; then
  ok "Claude memory already symlinked to Codex memory"
else
  rm -f "$CLAUDE_MEM"
  ln -s "$CODEX_MEM" "$CLAUDE_MEM"
  ok "linked $CLAUDE_MEM -> $CODEX_MEM"
fi

# ============================================================
# 9. Health check
# ============================================================
heading "9. Health check"
if [[ -x "$SKILL_DIR/doctor.sh" ]]; then
  bash "$SKILL_DIR/doctor.sh" || warn "doctor.sh reported issues"
fi

echo
ok "${B}setup complete.${X}"
echo
echo "  Try a dry-run:   bash $SKILL_DIR/calendar-plan.sh --dry-run"
echo "  Draft a plan:    bash $SKILL_DIR/calendar-plan.sh --mode draft"
echo
echo "  Re-run setup.sh any time you edit local.env."
echo "  Run sync.sh after editing prompts/cron-prompt.md or codex/SKILL.md."
