"""Render the /voice-check skill (SKILL.md) from a generated voice profile.

The generated skill is self-contained: it embeds the profile's hard-no lists and
targets so it works even without shell access, and it tells the agent to run the
deterministic checker when a shell is available.
"""

from __future__ import annotations

from pathlib import Path

from voice_check import profile as profile_mod

_TEMPLATE = """---
name: voice-check
description: Audit and rewrite a draft in the user's real voice using their generated voice profile. Use when reviewing or rewriting emails, posts, messages, or any personal writing.
---

# voice-check

Audit and rewrite drafts so they sound like the user's real voice, using the
deterministic voice profile in this repo. Default to **Audit**; switch to
**Rewrite** only when the user asks.

## Inputs
- Profile: `{profile_rules}` and `{profile_md}`.
- The draft: from the user, a file, or stdin.

## Procedure
1. If you have shell access, run the deterministic checker — it is the source of
   truth for the signals and score:
   ```bash
   python3 scripts/check_draft.py --draft <file>             # audit
   python3 scripts/check_draft.py --rewrite --draft <file>   # audit + baseline rewrite
   python3 scripts/check_draft.py --format json --draft <file>
   ```
   You can also pipe text on stdin instead of `--draft`.
2. If you do NOT have shell access, apply the rules in this file directly.
3. **Audit mode:** report the score, each violation with its fix, and what
   already matches the voice. Do not rewrite.
4. **Rewrite mode:** produce a revised draft that fixes every hard violation and
   as many soft ones as possible, WITHOUT inventing facts or changing meaning.
   Preserve the user's rhythm and directness. End with a 1-2 line rationale tied
   to the rules below.

## This voice in brief
- Written target derived from: **{derived_from}**.
- Sentence length: aim ~{mean} words (band {low}-{high}); vary it, don't make
  every sentence the same length.
- Contractions: use them (target ~{contraction} per 1k words).
- Em dashes: {em_dash_policy}.
- Vocabulary anchors (words that recur in this voice): {vocab}.

## Hard no list (never produce these)
- Corporate words: {corporate}.
- Generic-AI tells: {ai_tells}.
- Spoken filler left in writing: {filler}.
- Inflated claims without specifics: {inflated}.

## Privacy
Never quote raw lines from the user's corpus. Cite the profile's statistics
instead. The draft under review is the user's own text and may be quoted back.

---
_Generated by `scripts/build_skill.py` from your voice profile. Re-run it after
updating your corpus._
"""


def _join(items, limit=None) -> str:
    items = list(items)
    if limit and len(items) > limit:
        return ", ".join(items[:limit]) + f", … (+{len(items) - limit} more)"
    return ", ".join(items) if items else "(none recorded)"


def render_skill(rules: dict, profile_md: str, profile_dir: str = "data/profiles") -> str:
    band = rules.get("sentence_len_band", [0, 0])
    em_dash_policy = (
        "allowed (your profile uses them)"
        if rules.get("em_dash_allowed")
        else "never — replace with a period, comma, or parentheses"
    )
    return _TEMPLATE.format(
        profile_rules=f"{profile_dir}/voice_rules.json",
        profile_md=f"{profile_dir}/voice_profile.md",
        derived_from=rules.get("derived_from", "unknown"),
        mean=rules.get("sentence_len_mean", 0),
        low=band[0],
        high=band[1],
        contraction=rules.get("contraction_rate_target", 0),
        em_dash_policy=em_dash_policy,
        vocab=_join(rules.get("vocab_anchors", []), limit=20),
        corporate=_join(rules.get("corporate_blacklist", [])),
        ai_tells=_join(rules.get("ai_tells", [])),
        filler=_join(rules.get("filler_phrases", [])),
        inflated=_join(rules.get("inflated_phrases", [])),
    )


def write_skill(profile_dir, out_dir, targets=("claude", "codex")) -> list[Path]:
    profile_dir = Path(profile_dir)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    rules = profile_mod.load_rules(profile_dir)
    md_path = profile_dir / "voice_profile.md"
    profile_md = md_path.read_text(encoding="utf-8") if md_path.exists() else ""
    content = render_skill(rules, profile_md, profile_dir=str(profile_dir))

    written: list[Path] = []
    if "claude" in targets:
        path = out_dir / "SKILL.md"
        path.write_text(content, encoding="utf-8")
        written.append(path)
    if "codex" in targets:
        # Codex consumes prompt-style markdown; ship the same content as a
        # ready-to-copy prompt file alongside the Claude skill.
        path = out_dir / "voice-check.codex.md"
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
