#!/usr/bin/env bash
#
# setup.sh — single-command install for sync-phone (Claude Code + Codex CLI).
#
# Run after cloning:
#   bash setup.sh
#
# Reads local.env (creates from template on first run), then:
#   1. Symlinks ~/.claude/skills/sync-phone -> this repo's skills/sync-phone
#   2. Generates skills/sync-phone/config/settings.conf from local.env
#   3. Bootstraps Codex install (real-file copy of codex/SKILL.md + agents/openai.yaml)
#   4. Renders codex/automation.example.toml -> ~/.codex/automations/sync-phone/automation.toml (INACTIVE)
#   5. Ensures CAPTURE_DIR exists with iphone-raw.md + ingest.md + archive/
#   6. Runs doctor.sh

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$REPO_DIR/local.env"
ENV_EXAMPLE="$REPO_DIR/local.env.example"
SKILL_DIR="$REPO_DIR/skills/sync-phone"
CLAUDE_INSTALL="$HOME/.claude/skills/sync-phone"
CODEX_INSTALL="$HOME/.codex/skills/sync-phone"
CODEX_AUTO="$HOME/.codex/automations/sync-phone"

if [[ -t 1 ]]; then
  B=$'\e[1m'; D=$'\e[2m'; R=$'\e[31m'; G=$'\e[32m'; Y=$'\e[33m'; BL=$'\e[34m'; X=$'\e[0m'
else
  B=; D=; R=; G=; Y=; BL=; X=
fi
heading() { echo; echo "${B}${BL}== $1 ==${X}"; }
ok()      { echo "  ${G}OK${X}  $*"; }
warn()    { echo "  ${Y}WARN${X}  $*"; }
fail()    { echo "  ${R}FAIL${X}  $*"; }
skip()    { echo "  ${D}skip${X}  $*"; }

# ============================================================
# 0. local.env bootstrap
# ============================================================
heading "0. local.env"
if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$ENV_EXAMPLE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    warn "$ENV_FILE didn't exist — created from template."
    echo
    echo "  Default paths usually work. Review:"
    echo "    \$EDITOR $ENV_FILE"
    echo
    echo "  Then re-run:"
    echo "    bash $0"
    exit 1
  else
    fail "neither $ENV_FILE nor $ENV_EXAMPLE found. Re-clone the repo."
    exit 1
  fi
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a
ok "loaded $ENV_FILE"

# Defaults for any optional vars left unset
: "${CAPTURE_DIR:=$HOME/Library/Mobile Documents/com~apple~CloudDocs/_obsidian-capture}"
: "${VAULTS_DIR:=$HOME/Documents/Obsidian}"
: "${MODEL:=claude-sonnet-4-6}"
: "${TIMEZONE:=America/New_York}"
: "${CRON_HOUR:=22}"
: "${CODEX_MODEL:=gpt-5.5}"
: "${CODEX_REASONING:=xhigh}"
: "${CODEX_CWD:=$VAULTS_DIR}"

# ============================================================
# 1. Prereqs
# ============================================================
heading "1. Prereqs"
have_claude=0; have_codex=0
if command -v claude >/dev/null 2>&1; then
  ok "claude: $(claude --version 2>&1 | head -1)"; have_claude=1
else
  warn "claude not on PATH — Claude install will be skipped"
fi
if command -v codex >/dev/null 2>&1; then
  ok "codex:  $(codex --version 2>&1 | head -1)"; have_codex=1
else
  warn "codex not on PATH — Codex install will be skipped"
fi
if [[ $have_claude -eq 0 && $have_codex -eq 0 ]]; then
  fail "neither claude nor codex on PATH. Install at least one and re-run."
  exit 1
fi
command -v python3 >/dev/null 2>&1 || { fail "python3 required"; exit 1; }

# ============================================================
# 2. Claude install (symlink)
# ============================================================
heading "2. Claude install"
if [[ $have_claude -eq 1 ]]; then
  if [[ -L "$CLAUDE_INSTALL" ]]; then
    ok "already symlinked: $CLAUDE_INSTALL -> $(readlink "$CLAUDE_INSTALL")"
  elif [[ -d "$CLAUDE_INSTALL" ]]; then
    warn "$CLAUDE_INSTALL exists and is not a symlink. Leaving it alone."
  else
    mkdir -p "$(dirname "$CLAUDE_INSTALL")"
    ln -s "$SKILL_DIR" "$CLAUDE_INSTALL"
    ok "symlinked $CLAUDE_INSTALL -> $SKILL_DIR"
  fi
else
  skip "claude not installed; skipping Claude target"
fi

# ============================================================
# 3. settings.conf (shared between runtimes)
# ============================================================
heading "3. settings.conf (derived from local.env)"
mkdir -p "$SKILL_DIR/config"
cat > "$SKILL_DIR/config/settings.conf" <<EOF
# Auto-generated by setup.sh from local.env. Do not edit by hand — edit local.env instead.
CAPTURE_DIR="$CAPTURE_DIR"
VAULTS_DIR="$VAULTS_DIR"
MODEL="$MODEL"
TIMEZONE="$TIMEZONE"
EOF
chmod 600 "$SKILL_DIR/config/settings.conf"
ok "wrote $SKILL_DIR/config/settings.conf (chmod 600)"

# ============================================================
# 4. Codex install (real-file copy + automation render)
# ============================================================
heading "4. Codex install"
if [[ $have_codex -eq 1 ]]; then
  mkdir -p "$CODEX_INSTALL/agents" "$CODEX_INSTALL/config" "$CODEX_AUTO"

  cp "$REPO_DIR/codex/SKILL.md"                   "$CODEX_INSTALL/SKILL.md"
  cp "$REPO_DIR/codex/agents/openai.example.yaml" "$CODEX_INSTALL/agents/openai.yaml"
  cp "$SKILL_DIR/config/settings.conf"            "$CODEX_INSTALL/config/settings.conf"
  chmod 600 "$CODEX_INSTALL/config/settings.conf"
  ok "copied $CODEX_INSTALL/{SKILL.md, agents/openai.yaml, config/settings.conf}"

  # Render automation.toml (INACTIVE by default — opt-in cron).
  # Quoted heredoc + env passthrough so paths containing " or \ can't break Python literals.
  SRC_TOML="$REPO_DIR/codex/automation.example.toml" \
  OUT_TOML="$CODEX_AUTO/automation.toml" \
  V_CODEX_SKILL_DIR="$CODEX_INSTALL" \
  V_CODEX_AUTO_DIR="$CODEX_AUTO" \
  V_CAPTURE_DIR="$CAPTURE_DIR" \
  V_VAULTS_DIR="$VAULTS_DIR" \
  V_TIMEZONE="$TIMEZONE" \
  V_CRON_HOUR="$CRON_HOUR" \
  V_CODEX_CWD="$CODEX_CWD" \
  V_CODEX_MODEL="$CODEX_MODEL" \
  V_CODEX_REASONING="$CODEX_REASONING" \
  python3 - <<'PYEOF'
import os, pathlib, re
src = pathlib.Path(os.environ["SRC_TOML"]).read_text(encoding="utf-8")
mapping = {
    "{{CODEX_SKILL_DIR}}": os.environ["V_CODEX_SKILL_DIR"],
    "{{CODEX_AUTO_DIR}}":  os.environ["V_CODEX_AUTO_DIR"],
    "{{CAPTURE_DIR}}":     os.environ["V_CAPTURE_DIR"],
    "{{VAULTS_DIR}}":      os.environ["V_VAULTS_DIR"],
    "{{TIMEZONE}}":        os.environ["V_TIMEZONE"],
    "{{CRON_HOUR}}":       os.environ["V_CRON_HOUR"],
    "{{CODEX_CWD}}":       os.environ["V_CODEX_CWD"],
    "{{CODEX_MODEL}}":     os.environ["V_CODEX_MODEL"],
    "{{CODEX_REASONING}}": os.environ["V_CODEX_REASONING"],
}
out = src
for key, val in mapping.items():
    out = out.replace(key, val)
# Force INACTIVE — the user opts in to scheduled cron explicitly.
out = re.sub(r'^status\s*=\s*".*"', 'status = "INACTIVE"', out, count=1, flags=re.MULTILINE)
target = pathlib.Path(os.environ["OUT_TOML"])
target.write_text(out, encoding="utf-8")
print(f"  wrote {target} (status=INACTIVE — opt in by flipping the field)")
PYEOF
  ok "rendered $CODEX_AUTO/automation.toml"
else
  skip "codex not installed; skipping Codex target"
fi

# ============================================================
# 5. Capture directory bootstrap
# ============================================================
heading "5. Capture directory"
mkdir -p "$CAPTURE_DIR/archive"
[[ -f "$CAPTURE_DIR/iphone-raw.md" ]] || : > "$CAPTURE_DIR/iphone-raw.md"
[[ -f "$CAPTURE_DIR/ingest.md"     ]] || : > "$CAPTURE_DIR/ingest.md"
ok "ensured $CAPTURE_DIR/{iphone-raw.md, ingest.md, archive/}"

if [[ ! -d "$VAULTS_DIR" ]]; then
  warn "VAULTS_DIR ($VAULTS_DIR) does not exist yet — create it before running /sync-phone"
fi

# ============================================================
# 6. Health check
# ============================================================
heading "6. Health check"
if [[ $have_codex -eq 1 && -x "$REPO_DIR/codex/doctor.sh" ]]; then
  bash "$REPO_DIR/codex/doctor.sh" || warn "codex doctor.sh reported issues"
fi

echo
ok "${B}setup complete.${X}"
echo
if [[ $have_claude -eq 1 ]]; then
  echo "  Claude:  open Claude Code and run  /sync-phone"
fi
if [[ $have_codex -eq 1 ]]; then
  echo "  Codex:   restart codex, then either say"
  echo "             'drain my phone inbox'"
  echo "           or run the default prompt baked into agents/openai.yaml."
  echo "           (To enable the optional cron, edit $CODEX_AUTO/automation.toml"
  echo "            and set status = \"ACTIVE\".)"
fi
echo
echo "  Re-run this script any time you edit local.env."
echo "  Run sync.sh after editing codex/SKILL.md to push changes into the Codex install."
